/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#0050cb',
        'primary-container': '#0066ff',
        'primary-fixed': '#dae1ff',
        'primary-fixed-dim': '#b3c5ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#f8f7ff',
        'on-primary-fixed': '#001849',
        'on-primary-fixed-variant': '#003fa4',
        'secondary': '#006c49',
        'secondary-container': '#6cf8bb',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714d',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary': '#a33200',
        'tertiary-container': '#cc4204',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59d',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fff6f4',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary-fixed-variant': '#832600',
        'background': '#f9f9ff',
        'background-surface': '#FFFFFF',
        'background-subtle': '#F9FAFB',
        'surface': '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-dim': '#d0daef',
        'surface-container': '#e6eeff',
        'surface-container-low': '#eff3ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dee9fd',
        'surface-container-highest': '#d9e3f7',
        'surface-variant': '#d9e3f7',
        'surface-tint': '#0054d6',
        'on-background': '#121c2a',
        'on-surface': '#121c2a',
        'on-surface-variant': '#424656',
        'inverse-surface': '#273140',
        'inverse-on-surface': '#ebf1ff',
        'inverse-primary': '#b3c5ff',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'outline': '#727687',
        'outline-variant': '#c2c6d8',
        'ink-black': '#111827',
        'ink-gray': '#4B5563',
        'border-light': '#E5E7EB',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['56px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      spacing: {
        'margin-page': 'clamp(16px, 5vw, 40px)',
        'container-max': '1280px',
        'gutter-mobile': '16px',
        'gutter-desktop': '24px',
        'base': '4px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'soft': '0 4px 20px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}